// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3swVRkNnU7aVcupUqp-Y9QC4kob08L7U',
    appId: '1:491151736061:web:5c11f5b79ba85c0d505294',
    messagingSenderId: '491151736061',
    projectId: 'it-lap-4ade1',
    authDomain: 'it-lap-4ade1.firebaseapp.com',
    storageBucket: 'it-lap-4ade1.appspot.com',
    measurementId: 'G-4H04RH8PJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7cXXCEGmYQy8wXDMwc8W6tTpDEQD4O8',
    appId: '1:491151736061:android:1c3702f9b3ba59d6505294',
    messagingSenderId: '491151736061',
    projectId: 'it-lap-4ade1',
    storageBucket: 'it-lap-4ade1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6xs5vqS7Cuavev0YdPwFe89u6E6JWpk',
    appId: '1:491151736061:ios:2d43049cad61f92b505294',
    messagingSenderId: '491151736061',
    projectId: 'it-lap-4ade1',
    storageBucket: 'it-lap-4ade1.appspot.com',
    iosClientId: '491151736061-hnhsj73k2ci93vaf8035akk33d6ld7jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirstt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6xs5vqS7Cuavev0YdPwFe89u6E6JWpk',
    appId: '1:491151736061:ios:355da84a02f5116a505294',
    messagingSenderId: '491151736061',
    projectId: 'it-lap-4ade1',
    storageBucket: 'it-lap-4ade1.appspot.com',
    iosClientId: '491151736061-pt1vivgle8po6f846tf1pgrhl5aoqpu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirstt.RunnerTests',
  );
}
